# Generated by Django 3.2.12 on 2022-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_Appointments',
            fields=[
                ('appointemnt_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone_no', models.PositiveIntegerField(max_length=10)),
                ('department', models.CharField(choices=[('dept1', 'dept1'), ('dept2', 'dept2'), ('dept3', 'dept3'), ('dept4', 'dept4'), ('dept5', 'dept5')], default='dept1', max_length=20)),
                ('description', models.TextField(default='none')),
                ('slot', models.CharField(choices=[('morning', 'morning'), ('Evening', 'Evening'), ('day', 'day')], max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
