# Generated by Django 3.2.12 on 2022-12-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0003_have_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Whatsapp_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='related_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.dept'),
        ),
        migrations.AlterField(
            model_name='booking_appointments',
            name='department',
            field=models.ForeignKey(choices=[('dept1', 'dept1'), ('dept2', 'dept2'), ('dept3', 'dept3'), ('dept4', 'dept4'), ('dept5', 'dept5')], default='dept1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.dept'),
        ),
        migrations.AlterField(
            model_name='have_query',
            name='related_dept',
            field=models.ForeignKey(default='All_dept', null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.dept'),
        ),
    ]
