# Generated by Django 3.2.12 on 2022-12-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0004_auto_20221230_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_appointments',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.dept'),
        ),
    ]
