# Generated by Django 3.2.12 on 2022-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0005_alter_booking_appointments_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
